### ISSUE TITLE
Unexpected IntegrityError when Submitting Profile Edit Form for New Users

### ISSUE THREAD

**Issue by Crossroadsman** [Crossroadsman/treehouse-techdegree-python-project12#41]
### Issue ###

When a the profile edit form is submitted for a new user, an integrity error is generated (UNIQUE constraint failed `accounts_userprofile.user_id`).

### Steps to Recreate ###

- Create a new user
- Sign in as that user
- Navigate to /accounts/profile_edit
- Fill in the name/bio text
- Click Submit

Note that this bug does not seem to appear when updating a profile that already exists.

Note also that (at least with SQLite) the Integrity Error does not prevent the form data being
persisted to the database.

### Sample Error Text ###

Request Method: | POST
-- | --
http://localhost:8000/accounts/profile_edit
3.0.2
IntegrityError
UNIQUE constraint failed: accounts_userprofile.user_id

Request Method: POST
Request URL: http://localhost:8000/accounts/profile_edit

```
Traceback (most recent call last):
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (UNIQUE constraint failed: accounts_userprofile.user_id) was the direct cause of the following exception:
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/accounts/views.py", line 72, in profile_edit
    profile.save()
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1384, in execute_sql
    cursor.execute(sql, params)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/alexkoumparos/repos/treehouse-techdegree-python-project12/social_team_builder/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: IntegrityError at /accounts/profile_edit
Exception Value: UNIQUE constraint failed: accounts_userprofile.user_id
```

**Comment by Crossroadsman** [comment]
Issue related to implementation of multiple forms in single view. Fixed by rewriting views so that each view only has to take responsibility for processing a single form.
